### ISSUE TITLE
NameError: global name 'subprocess' is not defined

### ISSUE THREAD

**Issue by flipdazed** [jpn--/caffeine#1]
```
>>> caffeine.verify()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/caffeine.py", line 66, in verify
    subprocess.call(['pmset', '-g', 'assertions'])
NameError: global name 'subprocess' is not defined
```

Need the following in the file: `caffeine.py`

```
import subprocess
```

**Comment by jpn--** [comment]
Fixed  Thank you.
